version: '3'
services:
  db:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: dss
        MYSQL_USER: dss
        MYSQL_PASSWORD: dss
        MYSQL_DATABASE: dss
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:
      - 8080:8080
